// flow-typed signature: 19a661f8dea592c5b9c750a814b19a0f
// flow-typed version: <<STUB>>/axe-prop-types_v^1.0.8/flow_v0.85.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'axe-prop-types'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'axe-prop-types' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'axe-prop-types/index' {
  declare module.exports: $Exports<'axe-prop-types'>;
}
declare module 'axe-prop-types/index.js' {
  declare module.exports: $Exports<'axe-prop-types'>;
}
