// flow-typed signature: 079625c3d2fcf7a42e37b8fa909dfa89
// flow-typed version: <<STUB>>/axe-markdown-loader_v^2.0.5/flow_v0.85.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'axe-markdown-loader'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'axe-markdown-loader' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'axe-markdown-loader/dist/buildComponent' {
  declare module.exports: any;
}

declare module 'axe-markdown-loader/dist/parse' {
  declare module.exports: any;
}

declare module 'axe-markdown-loader/example/example' {
  declare module.exports: any;
}

declare module 'axe-markdown-loader/example/src/entry' {
  declare module.exports: any;
}

declare module 'axe-markdown-loader/example/src/TestComponent' {
  declare module.exports: any;
}

declare module 'axe-markdown-loader/index.development' {
  declare module.exports: any;
}

declare module 'axe-markdown-loader/index.production' {
  declare module.exports: any;
}

declare module 'axe-markdown-loader/src/buildComponent' {
  declare module.exports: any;
}

declare module 'axe-markdown-loader/src/components/ExampleRenderer' {
  declare module.exports: any;
}

declare module 'axe-markdown-loader/src/components/HtmlStyleTag' {
  declare module.exports: any;
}

declare module 'axe-markdown-loader/src/components/MarkdownComponent' {
  declare module.exports: any;
}

declare module 'axe-markdown-loader/src/components/PropsTable' {
  declare module.exports: any;
}

declare module 'axe-markdown-loader/src/imports/imports' {
  declare module.exports: any;
}

declare module 'axe-markdown-loader/src/parse' {
  declare module.exports: any;
}

declare module 'axe-markdown-loader/src/utils/hash' {
  declare module.exports: any;
}

declare module 'axe-markdown-loader/src/utils/parseStyle' {
  declare module.exports: any;
}

declare module 'axe-markdown-loader/tests/loader.test' {
  declare module.exports: any;
}

declare module 'axe-markdown-loader/webpack.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'axe-markdown-loader/dist/buildComponent.js' {
  declare module.exports: $Exports<'axe-markdown-loader/dist/buildComponent'>;
}
declare module 'axe-markdown-loader/dist/parse.js' {
  declare module.exports: $Exports<'axe-markdown-loader/dist/parse'>;
}
declare module 'axe-markdown-loader/example/example.js' {
  declare module.exports: $Exports<'axe-markdown-loader/example/example'>;
}
declare module 'axe-markdown-loader/example/src/entry.js' {
  declare module.exports: $Exports<'axe-markdown-loader/example/src/entry'>;
}
declare module 'axe-markdown-loader/example/src/TestComponent.js' {
  declare module.exports: $Exports<'axe-markdown-loader/example/src/TestComponent'>;
}
declare module 'axe-markdown-loader/index.development.js' {
  declare module.exports: $Exports<'axe-markdown-loader/index.development'>;
}
declare module 'axe-markdown-loader/index.production.js' {
  declare module.exports: $Exports<'axe-markdown-loader/index.production'>;
}
declare module 'axe-markdown-loader/src/buildComponent.js' {
  declare module.exports: $Exports<'axe-markdown-loader/src/buildComponent'>;
}
declare module 'axe-markdown-loader/src/components/ExampleRenderer.js' {
  declare module.exports: $Exports<'axe-markdown-loader/src/components/ExampleRenderer'>;
}
declare module 'axe-markdown-loader/src/components/HtmlStyleTag.js' {
  declare module.exports: $Exports<'axe-markdown-loader/src/components/HtmlStyleTag'>;
}
declare module 'axe-markdown-loader/src/components/MarkdownComponent.js' {
  declare module.exports: $Exports<'axe-markdown-loader/src/components/MarkdownComponent'>;
}
declare module 'axe-markdown-loader/src/components/PropsTable.js' {
  declare module.exports: $Exports<'axe-markdown-loader/src/components/PropsTable'>;
}
declare module 'axe-markdown-loader/src/imports/imports.js' {
  declare module.exports: $Exports<'axe-markdown-loader/src/imports/imports'>;
}
declare module 'axe-markdown-loader/src/parse.js' {
  declare module.exports: $Exports<'axe-markdown-loader/src/parse'>;
}
declare module 'axe-markdown-loader/src/utils/hash.js' {
  declare module.exports: $Exports<'axe-markdown-loader/src/utils/hash'>;
}
declare module 'axe-markdown-loader/src/utils/parseStyle.js' {
  declare module.exports: $Exports<'axe-markdown-loader/src/utils/parseStyle'>;
}
declare module 'axe-markdown-loader/tests/loader.test.js' {
  declare module.exports: $Exports<'axe-markdown-loader/tests/loader.test'>;
}
declare module 'axe-markdown-loader/webpack.config.js' {
  declare module.exports: $Exports<'axe-markdown-loader/webpack.config'>;
}
