// flow-typed signature: 95f7bedcb8e1abbfc2479167d4bdafcc
// flow-typed version: <<STUB>>/babel-plugin-static-fs_v^1.1.0/flow_v0.85.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-plugin-static-fs'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-plugin-static-fs' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'babel-plugin-static-fs/lib/fs' {
  declare module.exports: any;
}

declare module 'babel-plugin-static-fs/lib/get-module-function' {
  declare module.exports: any;
}

declare module 'babel-plugin-static-fs/lib/path' {
  declare module.exports: any;
}

declare module 'babel-plugin-static-fs/lib/static-eval' {
  declare module.exports: any;
}

// Filename aliases
declare module 'babel-plugin-static-fs/index' {
  declare module.exports: $Exports<'babel-plugin-static-fs'>;
}
declare module 'babel-plugin-static-fs/index.js' {
  declare module.exports: $Exports<'babel-plugin-static-fs'>;
}
declare module 'babel-plugin-static-fs/lib/fs.js' {
  declare module.exports: $Exports<'babel-plugin-static-fs/lib/fs'>;
}
declare module 'babel-plugin-static-fs/lib/get-module-function.js' {
  declare module.exports: $Exports<'babel-plugin-static-fs/lib/get-module-function'>;
}
declare module 'babel-plugin-static-fs/lib/path.js' {
  declare module.exports: $Exports<'babel-plugin-static-fs/lib/path'>;
}
declare module 'babel-plugin-static-fs/lib/static-eval.js' {
  declare module.exports: $Exports<'babel-plugin-static-fs/lib/static-eval'>;
}
