// flow-typed signature: 788541df61c3d1195024a1891b89e5ab
// flow-typed version: <<STUB>>/eslint-sammy-preset_v^7.3.0/flow_v0.85.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-sammy-preset'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-sammy-preset' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'eslint-sammy-preset/index' {
  declare module.exports: $Exports<'eslint-sammy-preset'>;
}
declare module 'eslint-sammy-preset/index.js' {
  declare module.exports: $Exports<'eslint-sammy-preset'>;
}
