// flow-typed signature: 3d8b5d84e44692474ce24ca5b0c67cdc
// flow-typed version: <<STUB>>/geckodriver_v^1.12.2/flow_v0.85.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'geckodriver'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'geckodriver' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'geckodriver/lib/geckodriver' {
  declare module.exports: any;
}

declare module 'geckodriver/test/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'geckodriver/index' {
  declare module.exports: $Exports<'geckodriver'>;
}
declare module 'geckodriver/index.js' {
  declare module.exports: $Exports<'geckodriver'>;
}
declare module 'geckodriver/lib/geckodriver.js' {
  declare module.exports: $Exports<'geckodriver/lib/geckodriver'>;
}
declare module 'geckodriver/test/index.js' {
  declare module.exports: $Exports<'geckodriver/test/index'>;
}
