// flow-typed signature: 68f3383ba020b2ed9b8bf1a0437da5f6
// flow-typed version: <<STUB>>/generate-asset-webpack-plugin_v^0.3.0/flow_v0.85.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'generate-asset-webpack-plugin'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'generate-asset-webpack-plugin' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'generate-asset-webpack-plugin/dist/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'generate-asset-webpack-plugin/dist/index.js' {
  declare module.exports: $Exports<'generate-asset-webpack-plugin/dist/index'>;
}
declare module 'generate-asset-webpack-plugin/index' {
  declare module.exports: $Exports<'generate-asset-webpack-plugin'>;
}
declare module 'generate-asset-webpack-plugin/index.js' {
  declare module.exports: $Exports<'generate-asset-webpack-plugin'>;
}
