// flow-typed signature: 81bc3f103a0becae192259e27ff88281
// flow-typed version: <<STUB>>/jsonminify_v^0.4.1/flow_v0.85.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'jsonminify'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'jsonminify' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'jsonminify/docs/scripts/linenumber' {
  declare module.exports: any;
}

declare module 'jsonminify/docs/scripts/prettify/lang-css' {
  declare module.exports: any;
}

declare module 'jsonminify/docs/scripts/prettify/prettify' {
  declare module.exports: any;
}

declare module 'jsonminify/minify.json' {
  declare module.exports: any;
}

declare module 'jsonminify/report/assets/scripts/bundles/codemirror' {
  declare module.exports: any;
}

declare module 'jsonminify/report/assets/scripts/bundles/core-bundle' {
  declare module.exports: any;
}

declare module 'jsonminify/report/assets/scripts/codemirror.markpopovertext' {
  declare module.exports: any;
}

declare module 'jsonminify/report/assets/scripts/plato-display' {
  declare module.exports: any;
}

declare module 'jsonminify/report/assets/scripts/plato-file' {
  declare module.exports: any;
}

declare module 'jsonminify/report/assets/scripts/plato-overview' {
  declare module.exports: any;
}

declare module 'jsonminify/report/assets/scripts/plato-sortable-file-list' {
  declare module.exports: any;
}

declare module 'jsonminify/report/assets/scripts/vendor/bootstrap-popover' {
  declare module.exports: any;
}

declare module 'jsonminify/report/assets/scripts/vendor/bootstrap-tooltip' {
  declare module.exports: any;
}

declare module 'jsonminify/report/assets/scripts/vendor/codemirror/codemirror' {
  declare module.exports: any;
}

declare module 'jsonminify/report/assets/scripts/vendor/codemirror/javascript' {
  declare module.exports: any;
}

declare module 'jsonminify/report/assets/scripts/vendor/codemirror/util/closetag' {
  declare module.exports: any;
}

declare module 'jsonminify/report/assets/scripts/vendor/codemirror/util/colorize' {
  declare module.exports: any;
}

declare module 'jsonminify/report/assets/scripts/vendor/codemirror/util/continuecomment' {
  declare module.exports: any;
}

declare module 'jsonminify/report/assets/scripts/vendor/codemirror/util/continuelist' {
  declare module.exports: any;
}

declare module 'jsonminify/report/assets/scripts/vendor/codemirror/util/dialog' {
  declare module.exports: any;
}

declare module 'jsonminify/report/assets/scripts/vendor/codemirror/util/foldcode' {
  declare module.exports: any;
}

declare module 'jsonminify/report/assets/scripts/vendor/codemirror/util/formatting' {
  declare module.exports: any;
}

declare module 'jsonminify/report/assets/scripts/vendor/codemirror/util/javascript-hint' {
  declare module.exports: any;
}

declare module 'jsonminify/report/assets/scripts/vendor/codemirror/util/loadmode' {
  declare module.exports: any;
}

declare module 'jsonminify/report/assets/scripts/vendor/codemirror/util/match-highlighter' {
  declare module.exports: any;
}

declare module 'jsonminify/report/assets/scripts/vendor/codemirror/util/matchbrackets' {
  declare module.exports: any;
}

declare module 'jsonminify/report/assets/scripts/vendor/codemirror/util/multiplex' {
  declare module.exports: any;
}

declare module 'jsonminify/report/assets/scripts/vendor/codemirror/util/overlay' {
  declare module.exports: any;
}

declare module 'jsonminify/report/assets/scripts/vendor/codemirror/util/pig-hint' {
  declare module.exports: any;
}

declare module 'jsonminify/report/assets/scripts/vendor/codemirror/util/runmode-standalone' {
  declare module.exports: any;
}

declare module 'jsonminify/report/assets/scripts/vendor/codemirror/util/runmode' {
  declare module.exports: any;
}

declare module 'jsonminify/report/assets/scripts/vendor/codemirror/util/search' {
  declare module.exports: any;
}

declare module 'jsonminify/report/assets/scripts/vendor/codemirror/util/searchcursor' {
  declare module.exports: any;
}

declare module 'jsonminify/report/assets/scripts/vendor/codemirror/util/simple-hint' {
  declare module.exports: any;
}

declare module 'jsonminify/report/assets/scripts/vendor/codemirror/util/xml-hint' {
  declare module.exports: any;
}

declare module 'jsonminify/report/assets/scripts/vendor/jquery-1.8.3.min' {
  declare module.exports: any;
}

declare module 'jsonminify/report/assets/scripts/vendor/jquery.fittext' {
  declare module.exports: any;
}

declare module 'jsonminify/report/assets/scripts/vendor/lodash.min' {
  declare module.exports: any;
}

declare module 'jsonminify/report/assets/scripts/vendor/morris.min' {
  declare module.exports: any;
}

declare module 'jsonminify/report/assets/scripts/vendor/raphael-min' {
  declare module.exports: any;
}

declare module 'jsonminify/report/files/minify_json_js/report.history' {
  declare module.exports: any;
}

declare module 'jsonminify/report/files/minify_json_js/report' {
  declare module.exports: any;
}

declare module 'jsonminify/report/report.history' {
  declare module.exports: any;
}

declare module 'jsonminify/report/report' {
  declare module.exports: any;
}

declare module 'jsonminify/test/test-minify.json' {
  declare module.exports: any;
}

// Filename aliases
declare module 'jsonminify/docs/scripts/linenumber.js' {
  declare module.exports: $Exports<'jsonminify/docs/scripts/linenumber'>;
}
declare module 'jsonminify/docs/scripts/prettify/lang-css.js' {
  declare module.exports: $Exports<'jsonminify/docs/scripts/prettify/lang-css'>;
}
declare module 'jsonminify/docs/scripts/prettify/prettify.js' {
  declare module.exports: $Exports<'jsonminify/docs/scripts/prettify/prettify'>;
}
declare module 'jsonminify/minify.json.js' {
  declare module.exports: $Exports<'jsonminify/minify.json'>;
}
declare module 'jsonminify/report/assets/scripts/bundles/codemirror.js' {
  declare module.exports: $Exports<'jsonminify/report/assets/scripts/bundles/codemirror'>;
}
declare module 'jsonminify/report/assets/scripts/bundles/core-bundle.js' {
  declare module.exports: $Exports<'jsonminify/report/assets/scripts/bundles/core-bundle'>;
}
declare module 'jsonminify/report/assets/scripts/codemirror.markpopovertext.js' {
  declare module.exports: $Exports<'jsonminify/report/assets/scripts/codemirror.markpopovertext'>;
}
declare module 'jsonminify/report/assets/scripts/plato-display.js' {
  declare module.exports: $Exports<'jsonminify/report/assets/scripts/plato-display'>;
}
declare module 'jsonminify/report/assets/scripts/plato-file.js' {
  declare module.exports: $Exports<'jsonminify/report/assets/scripts/plato-file'>;
}
declare module 'jsonminify/report/assets/scripts/plato-overview.js' {
  declare module.exports: $Exports<'jsonminify/report/assets/scripts/plato-overview'>;
}
declare module 'jsonminify/report/assets/scripts/plato-sortable-file-list.js' {
  declare module.exports: $Exports<'jsonminify/report/assets/scripts/plato-sortable-file-list'>;
}
declare module 'jsonminify/report/assets/scripts/vendor/bootstrap-popover.js' {
  declare module.exports: $Exports<'jsonminify/report/assets/scripts/vendor/bootstrap-popover'>;
}
declare module 'jsonminify/report/assets/scripts/vendor/bootstrap-tooltip.js' {
  declare module.exports: $Exports<'jsonminify/report/assets/scripts/vendor/bootstrap-tooltip'>;
}
declare module 'jsonminify/report/assets/scripts/vendor/codemirror/codemirror.js' {
  declare module.exports: $Exports<'jsonminify/report/assets/scripts/vendor/codemirror/codemirror'>;
}
declare module 'jsonminify/report/assets/scripts/vendor/codemirror/javascript.js' {
  declare module.exports: $Exports<'jsonminify/report/assets/scripts/vendor/codemirror/javascript'>;
}
declare module 'jsonminify/report/assets/scripts/vendor/codemirror/util/closetag.js' {
  declare module.exports: $Exports<'jsonminify/report/assets/scripts/vendor/codemirror/util/closetag'>;
}
declare module 'jsonminify/report/assets/scripts/vendor/codemirror/util/colorize.js' {
  declare module.exports: $Exports<'jsonminify/report/assets/scripts/vendor/codemirror/util/colorize'>;
}
declare module 'jsonminify/report/assets/scripts/vendor/codemirror/util/continuecomment.js' {
  declare module.exports: $Exports<'jsonminify/report/assets/scripts/vendor/codemirror/util/continuecomment'>;
}
declare module 'jsonminify/report/assets/scripts/vendor/codemirror/util/continuelist.js' {
  declare module.exports: $Exports<'jsonminify/report/assets/scripts/vendor/codemirror/util/continuelist'>;
}
declare module 'jsonminify/report/assets/scripts/vendor/codemirror/util/dialog.js' {
  declare module.exports: $Exports<'jsonminify/report/assets/scripts/vendor/codemirror/util/dialog'>;
}
declare module 'jsonminify/report/assets/scripts/vendor/codemirror/util/foldcode.js' {
  declare module.exports: $Exports<'jsonminify/report/assets/scripts/vendor/codemirror/util/foldcode'>;
}
declare module 'jsonminify/report/assets/scripts/vendor/codemirror/util/formatting.js' {
  declare module.exports: $Exports<'jsonminify/report/assets/scripts/vendor/codemirror/util/formatting'>;
}
declare module 'jsonminify/report/assets/scripts/vendor/codemirror/util/javascript-hint.js' {
  declare module.exports: $Exports<'jsonminify/report/assets/scripts/vendor/codemirror/util/javascript-hint'>;
}
declare module 'jsonminify/report/assets/scripts/vendor/codemirror/util/loadmode.js' {
  declare module.exports: $Exports<'jsonminify/report/assets/scripts/vendor/codemirror/util/loadmode'>;
}
declare module 'jsonminify/report/assets/scripts/vendor/codemirror/util/match-highlighter.js' {
  declare module.exports: $Exports<'jsonminify/report/assets/scripts/vendor/codemirror/util/match-highlighter'>;
}
declare module 'jsonminify/report/assets/scripts/vendor/codemirror/util/matchbrackets.js' {
  declare module.exports: $Exports<'jsonminify/report/assets/scripts/vendor/codemirror/util/matchbrackets'>;
}
declare module 'jsonminify/report/assets/scripts/vendor/codemirror/util/multiplex.js' {
  declare module.exports: $Exports<'jsonminify/report/assets/scripts/vendor/codemirror/util/multiplex'>;
}
declare module 'jsonminify/report/assets/scripts/vendor/codemirror/util/overlay.js' {
  declare module.exports: $Exports<'jsonminify/report/assets/scripts/vendor/codemirror/util/overlay'>;
}
declare module 'jsonminify/report/assets/scripts/vendor/codemirror/util/pig-hint.js' {
  declare module.exports: $Exports<'jsonminify/report/assets/scripts/vendor/codemirror/util/pig-hint'>;
}
declare module 'jsonminify/report/assets/scripts/vendor/codemirror/util/runmode-standalone.js' {
  declare module.exports: $Exports<'jsonminify/report/assets/scripts/vendor/codemirror/util/runmode-standalone'>;
}
declare module 'jsonminify/report/assets/scripts/vendor/codemirror/util/runmode.js' {
  declare module.exports: $Exports<'jsonminify/report/assets/scripts/vendor/codemirror/util/runmode'>;
}
declare module 'jsonminify/report/assets/scripts/vendor/codemirror/util/search.js' {
  declare module.exports: $Exports<'jsonminify/report/assets/scripts/vendor/codemirror/util/search'>;
}
declare module 'jsonminify/report/assets/scripts/vendor/codemirror/util/searchcursor.js' {
  declare module.exports: $Exports<'jsonminify/report/assets/scripts/vendor/codemirror/util/searchcursor'>;
}
declare module 'jsonminify/report/assets/scripts/vendor/codemirror/util/simple-hint.js' {
  declare module.exports: $Exports<'jsonminify/report/assets/scripts/vendor/codemirror/util/simple-hint'>;
}
declare module 'jsonminify/report/assets/scripts/vendor/codemirror/util/xml-hint.js' {
  declare module.exports: $Exports<'jsonminify/report/assets/scripts/vendor/codemirror/util/xml-hint'>;
}
declare module 'jsonminify/report/assets/scripts/vendor/jquery-1.8.3.min.js' {
  declare module.exports: $Exports<'jsonminify/report/assets/scripts/vendor/jquery-1.8.3.min'>;
}
declare module 'jsonminify/report/assets/scripts/vendor/jquery.fittext.js' {
  declare module.exports: $Exports<'jsonminify/report/assets/scripts/vendor/jquery.fittext'>;
}
declare module 'jsonminify/report/assets/scripts/vendor/lodash.min.js' {
  declare module.exports: $Exports<'jsonminify/report/assets/scripts/vendor/lodash.min'>;
}
declare module 'jsonminify/report/assets/scripts/vendor/morris.min.js' {
  declare module.exports: $Exports<'jsonminify/report/assets/scripts/vendor/morris.min'>;
}
declare module 'jsonminify/report/assets/scripts/vendor/raphael-min.js' {
  declare module.exports: $Exports<'jsonminify/report/assets/scripts/vendor/raphael-min'>;
}
declare module 'jsonminify/report/files/minify_json_js/report.history.js' {
  declare module.exports: $Exports<'jsonminify/report/files/minify_json_js/report.history'>;
}
declare module 'jsonminify/report/files/minify_json_js/report.js' {
  declare module.exports: $Exports<'jsonminify/report/files/minify_json_js/report'>;
}
declare module 'jsonminify/report/report.history.js' {
  declare module.exports: $Exports<'jsonminify/report/report.history'>;
}
declare module 'jsonminify/report/report.js' {
  declare module.exports: $Exports<'jsonminify/report/report'>;
}
declare module 'jsonminify/test/test-minify.json.js' {
  declare module.exports: $Exports<'jsonminify/test/test-minify.json'>;
}
