// flow-typed signature: 48608aedf315cc385921509aca0f813e
// flow-typed version: <<STUB>>/object-filter_v^1.0.2/flow_v0.85.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'object-filter'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'object-filter' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'object-filter/test/simple-test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'object-filter/index' {
  declare module.exports: $Exports<'object-filter'>;
}
declare module 'object-filter/index.js' {
  declare module.exports: $Exports<'object-filter'>;
}
declare module 'object-filter/test/simple-test.js' {
  declare module.exports: $Exports<'object-filter/test/simple-test'>;
}
