// flow-typed signature: 3693f3a85dbc78551b058ac088892c30
// flow-typed version: <<STUB>>/reduce-object_v^0.1.3/flow_v0.85.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'reduce-object'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'reduce-object' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'reduce-object/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'reduce-object/index' {
  declare module.exports: $Exports<'reduce-object'>;
}
declare module 'reduce-object/index.js' {
  declare module.exports: $Exports<'reduce-object'>;
}
declare module 'reduce-object/test.js' {
  declare module.exports: $Exports<'reduce-object/test'>;
}
