branch-defaults:
  master:
    environment: production
    group_suffix: null
global:
  application_name: react-graphql-app-boilerplate
  branch: null
  default_ec2_keyname: null
  default_platform: Docker 17.12.1-ce
  default_region: eu-west-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  repository: null
  sc: git
  workspace_type: Application
