version: 2
jobs:
  test:
    working_directory: ~/app
    docker:
      - image: circleci/node:11.4.0-browsers
    steps:
      - checkout

      # Download and cache yarn dependencies
      - restore_cache:
          keys:
            # Find a cache corresponding to this specific package.json checksum
            # when this file is changed, this key will fail
            - app-dependencies-{{ checksum "package.json" }}
            - app-dependencies-

      - run:
          name: Install yarn dependencies
          command: yarn install

      - run:
          name: Run linter
          command: yarn lint

      - run:
          name: Run flow validation
          command: yarn gql-flow && yarn flow

      - run:
          name: Run tests
          command: yarn test

      - run:
          name: Build application
          command: yarn build

  push-docker-image:
    working_directory: ~/app
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - setup_remote_docker

      - run:
          name: Install AWS CLI tools
          command: |
            curl "https://s3.amazonaws.com/aws-cli/awscli-bundle.zip" -o "awscli-bundle.zip"
            unzip awscli-bundle.zip
            sudo ./awscli-bundle/install -i /usr/local/aws -b /usr/local/bin/aws

      - run:
          name: 'Log in to AWS ECR'
          command: eval $(aws ecr get-login --no-include-email --region eu-west-1)

      - run:
          name: 'Build & Push Docker Image'
          command: |
            docker build -t $AWS_ACCOUNT_ID.dkr.ecr.eu-west-1.amazonaws.com/react-graphql-app-boilerplate:latest -t $AWS_ACCOUNT_ID.dkr.ecr.eu-west-1.amazonaws.com/react-graphql-app-boilerplate:latest .
            docker push $AWS_ACCOUNT_ID.dkr.ecr.eu-west-1.amazonaws.com/react-graphql-app-boilerplate:latest

  deploy:
    working_directory: ~/app
    docker:
      - image: circleci/node:11.4.0-browsers
    steps:
      - checkout

      - run:
          name: Install EB deployment dependencies
          working_directory: /
          command: |
            sudo apt-get -y -qq update
            sudo apt-get install python-pip python-dev build-essential
            sudo pip install awsebcli --upgrade

      - run:
          name: Deploy to EB
          command: eb deploy

workflows:
  version: 2
  build:
    jobs:
      - test

      - push-docker-image:
          requires:
            - test

          filters:
            branches:
              only:
                - staging
                - master

      - deploy:
          requires:
            - test
            - push-docker-image

          filters:
            branches:
              only:
                - staging
                - master
